<div class="backShadow"><!-- --></div>
<div class="callBack">
    <a href="#" class="closeCallBack"><!-- --></a>
    <h2><?php echo $this->__('Call me back') ?></h2>
    <div class="callBackContent">
        <form action="<?php echo Mage::helper('dev_callback')->getCallbackPostUrl() ?>" method="post" id="callBackForm">

            <ul class="form-list">
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label class="required" for="cbfirstname"><em>*</em><?php echo $this->__('NAME:') ?></label>
                            <div class="input-box">
                                <input type="text" class="input-text required-entry" maxlength="255" title="<?php echo $this->__('NAME:') ?>" value="" name="cbfirstname" id="cbfirstname">
                            </div>
                        </div>
                        <div class="field name-lastname">
                            <label class="required" for="cblastname"><em>*</em><?php echo $this->__('SURNAME:') ?></label>
                            <div class="input-box">
                                <input type="text" class="input-text required-entry" maxlength="255" title="<?php echo $this->__('SURNAME:') ?>" value="" name="cblastname" id="cblastname">
                            </div>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label class="required" for="cbphone"><em>*</em><?php echo $this->__('PHONE:') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" maxlength="255" title="<?php echo $this->__('PHONE:') ?>" value="" name="cbphone" id="cbphone">
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label class="required" for="cbquestion"><em>*</em><?php echo $this->__('QUESTION:') ?></label>
                        <div class="input-box">
                            <textarea name="cbquestion" id="cbquestion" class="required-entry"></textarea>
                        </div>
                    </div>
                </li>
                <li class="buttons-set">
                    <button class="button btn-black" title="<?php echo $this->__('Send') ?>" type="submit"><span><span><?php echo $this->__('Send') ?></span></span></button>
                </li>
            </ul>

        </form>
        <div class="callBackMessage cbm-success"><?php echo $this->__('Your request is recieved') ?></div>
        <div class="callBackMessage cbm-error"><?php echo $this->__('There is some error') ?></div>
    </div>
</div>
<script type="text/javascript">
        var callBack =  function (el) {
            this.el = jQuery(el);
            this.shadow = this.el.prev();
            this.form = this.el.find('form');
            this.magentoForm =  new VarienForm('callBackForm',true);
            this.messages = this.el.find('.callBackMessage');
            this.close = this.el.find('.closeCallBack');
        };

        callBack.prototype.init = function(){

            var self = this;
            this.close.on('click',function(e){
                e.preventDefault();
                self.hide();
            });
            this.el.find('.button').on('click',function(e){
                e.preventDefault();
                self.send();
            })
        };

        callBack.prototype.show = function(){
            this.shadow.show();
            this.el.show();
            this.form.show();
            this.messages.hide();

        };
        callBack.prototype.hide = function(){
            this.shadow.hide();
            this.el.hide();
        };

        callBack.prototype.send = function(){
            var self = this;

            self.magentoForm.validator.validate() && jQuery.ajax(self.form.attr('action'), {
                data : self.form.serialize() ,
                method: 'POST',
                success : function( data ) {
                    self.form.hide();
                    self.el.find('.cbm-success').show();
                    setTimeout(function(){
                        self.hide();
                    },3000);
                },
                error : function(){
                    self.form.hide();
                    self.el.find('.cbm-error').show();
                    setTimeout(function(){
                        self.hide();
                    },3000);
                }

            })
        };

        var callMe = new callBack('.callBack');
        callMe.init();

</script>