<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
ob_start();
if (isset($_GET['id'])) {
    $option = $_GET['cat'] . $_GET['id'];
    ?>    <?php
    $producer = Mage::getModel('banner_producer/producer')->load($option, 'option_proizv');
    ?>    <?php
    if ($producer and $producer->getId()):
        ?>
        <div style='margin-bottom:20px;'>
            <div style='text-align: center;margin-bottom: 15px;font-size:20px;color:#04538B;width:700px;margin-left:10px;margin-top:20px;'><?php
                echo $producer->getNameProizv();
                ?></div>
            <img class='img_view_proizv' src='/img/<?php
            echo $producer->getImgProizv();
            ?>' style='width:150px;text-align:left;float:left;margin-right:10px;' />

            <div style='margin-left:10px;font-size:14px;width:700px;margin-top:10px;margin-bottom:10px;margin-left:10px;'><?php
                echo $producer->getDescProizv();
                ?></div>
            <div style='clear:both;'></div>
        </div>    <?php
    endif;
    ?>    <?php
}
?><?php
if (!$_productCollection->count()):
    ?>    <!--<p class="note-msg"><?php
    echo $this->__('There are no products matching the selection.');
?></p>--><?php else:
    ?>
    <div class="category-products">        <?php // List mode
        ?>        <?php
        if ($this->getMode() != 'grid'):
            ?>            <?php
            $_iterator = 0;
            ?>
            <ol class="products-list" id="products-list">                <?php
                foreach ($_productCollection as $_product):
                    ?>
                    <li class="item<?php
                    if (++$_iterator == sizeof($_productCollection)):
                        ?> last<?php
                    endif;
                    ?>">                        <?php // Product Image
                        ?>                        <a href="<?php
                        echo $_product->getProductUrl();
                        ?>" title="<?php
                        echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
                        ?>" class="product-image"><img src="<?php
                            echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(185);
                            ?>" alt="<?php
                            echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
                            ?>" /></a>                        <?php // Product description
                        ?>
                        <div class="product-shop">
                            <div class="f-fix">                                <?php
                                $_productNameStripped = $this->stripTags($_product->getName(), null, true);
                                ?>                                <h2 class="product-name"><a href="<?php
                                    echo $_product->getProductUrl();
                                    ?>" title="<?php
                                    echo $_productNameStripped;
                                    ?>"><?php
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                                        ?></a></h2>

                                <div class="desc std">                                    <?php
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                                    ?>                                    <a href="<?php
                                    echo $_product->getProductUrl();
                                    ?>" title="<?php
                                    echo $_productNameStripped;
                                    ?>" class="link-learn"><?php
                                        echo $this->__('Learn More');
                                        ?></a></div>                                <?php
                                echo $this->getPriceHtml($_product, true);
                                ?>                                <?php
                                if ($_product->isSaleable()):
                                    ?>
                                    <p>
                                        <button type="button" title="<?php
                                        echo $this->__('Add to Cart');
                                        ?>" class="button btn-cart" onclick="setLocation('<?php
                                        echo $this->getAddToCartUrl($_product);
                                        ?>')"><span><span><?php
                                                    echo $this->__('Add to Cart');
                                                    ?></span></span></button>
                                    </p>                                <?php else:
                                    ?>                                    <p class="availability out-of-stock"><span><?php
                                        echo $this->__('Out of stock');
                                        ?></span></p>                                <?php
                                endif;
                                ?>
                                <ul class="add-to-links">                                    <?php
                                    if ($this->helper('wishlist')->isAllow()):
                                        ?>
                                        <li><a href="<?php
                                            echo $this->helper('wishlist')->getAddUrl($_product);
                                            ?>" class="link-wishlist"><?php
                                                echo $this->__('Add to Wishlist');
                                                ?></a></li>                                    <?php
                                    endif;
                                    ?>                                    <?php
                                    if ($_compareUrl = $this->getAddToCompareUrl($_product)):
                                        ?>
                                        <li><span class="separator">|</span> <a href="<?php
                                            echo $_compareUrl;
                                            ?>" class="link-compare"><?php
                                                echo $this->__('Add to Compare');
                                                ?></a></li>                                    <?php
                                    endif;
                                    ?>                                </ul>
                            </div>
                        </div>
                    </li>                <?php
                endforeach;
                ?>            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>        <?php
        else:
            ?>            <?php // Grid Mode
            ?>            <?php
            $_collectionSize = $_productCollection->count()?>            <?php
            $_columnCount = 3;
            ?>            <?php
            $i = 0;
        foreach ($_productCollection as $_product):
            ?>            <?php
        if ($i++ % $_columnCount == 0):
            ?>            <ul class="products-grid">        <?php
        endif;
            ?>
            <li class="item<?php
            if (($i - 1) % $_columnCount == 0):
                ?> first<?php elseif ($i % $_columnCount == 0):
                ?> last<?php
            endif;
            ?>"><h2 class="product-name"><a href="<?php
                    echo $_product->getProductUrl();
                    ?>" title="<?php
                    echo $this->stripTags($_product->getName(), null, true);
                    ?>"><?php
                        echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                        ?></a></h2>                <a href="<?php
                echo $_product->getProductUrl();
                ?>" title="<?php
                echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
                ?>" class="product-image"><img src="<?php
                    echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(185);
                    ?>" alt="<?php
                    echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
                    ?>" /></a>                <?php
                echo $this->getPriceHtml($_product, true);
                ?>
                <div class="actions">                    <?php
                    if ($_product->isSaleable()):
                        ?>
                        <button type="button" title="<?php
                        echo $this->__('Add to Cart');
                        ?>" class="button btn-cart" onclick="setLocation('<?php
                        echo $this->getAddToCartUrl($_product);
                        ?>')"><span><span><?php
                                    echo $this->__('Add to Cart');
                                    ?></span></span></button>                    <?php else:
                        ?>                        <p class="availability out-of-stock"><span><?php
                            echo $this->__('Out of stock');
                            ?></span></p>                    <?php
                    endif;
                    ?>                </div>
            </li>            <?php
        if ($i % $_columnCount == 0 || $i == $_collectionSize):
            ?>            </ul>        <?php
        endif;
            ?>        <?php
        endforeach;
            ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>        <?php
        endif;
        ?>    </div>
    <div class="toolbar-bottom">        <?php
    echo $this->getToolbarHtml();
    ?>    </div><?php
endif;
global $proizv;
$proizv = ob_get_contents();
ob_end_clean();
?>